package com.ihesen.think.utils.db.tables;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.NotNull;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "ACTIVITY".
 */
@Entity
public class Activity {

    @Id
    private Long id;

    @NotNull
    private String userId;
    private String username;
    private String message;
    private String pulish;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Activity() {
    }

    public Activity(Long id) {
        this.id = id;
    }

    @Generated
    public Activity(Long id, String userId, String username, String message, String pulish) {
        this.id = id;
        this.userId = userId;
        this.username = username;
        this.message = message;
        this.pulish = pulish;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getUserId() {
        return userId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserId(@NotNull String userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getPulish() {
        return pulish;
    }

    public void setPulish(String pulish) {
        this.pulish = pulish;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
