package com.ihesen.think.utils.db.tables;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "TEST_TABLE".
 */
public class TestTable {

    private Long id;
    private Integer testInt;

    public TestTable() {
    }

    public TestTable(Long id) {
        this.id = id;
    }

    public TestTable(Long id, Integer testInt) {
        this.id = id;
        this.testInt = testInt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getTestInt() {
        return testInt;
    }

    public void setTestInt(Integer testInt) {
        this.testInt = testInt;
    }

}
