package com.ihesen.think.utils.db.tables;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TEST_TABLE".
 */
@Entity
public class TestTable {

    @Id
    private Long id;
    private Integer testInt;

    @Generated
    public TestTable() {
    }

    public TestTable(Long id) {
        this.id = id;
    }

    @Generated
    public TestTable(Long id, Integer testInt) {
        this.id = id;
        this.testInt = testInt;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getTestInt() {
        return testInt;
    }

    public void setTestInt(Integer testInt) {
        this.testInt = testInt;
    }

}
