package com.ihesen.think.utils.db;

import android.database.sqlite.SQLiteDatabase;

import com.ihesen.think.utils.db.daos.ActivityDao;
import com.ihesen.think.utils.db.tables.Activity;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig activityDaoConfig;

    private final ActivityDao activityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig> daoConfigMap) {
        super(db);

        activityDaoConfig = daoConfigMap.get(ActivityDao.class).clone();
        activityDaoConfig.initIdentityScope(type);

        activityDao = new ActivityDao(activityDaoConfig, this);

        registerDao(Activity.class, activityDao);
    }

    public void clear() {
        activityDaoConfig.getIdentityScope().clear();
    }

    public ActivityDao getActivityDao() {
        return activityDao;
    }

}
