package com.ihesen.think.utils.db;

import com.ihesen.think.utils.db.daos.ActivityDao;
import com.ihesen.think.utils.db.daos.TestTableDao;
import com.ihesen.think.utils.db.tables.Activity;
import com.ihesen.think.utils.db.tables.TestTable;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig activityDaoConfig;
    private final DaoConfig testTableDaoConfig;

    private final ActivityDao activityDao;
    private final TestTableDao testTableDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        activityDaoConfig = daoConfigMap.get(ActivityDao.class).clone();
        activityDaoConfig.initIdentityScope(type);

        testTableDaoConfig = daoConfigMap.get(TestTableDao.class).clone();
        testTableDaoConfig.initIdentityScope(type);

        activityDao = new ActivityDao(activityDaoConfig, this);
        testTableDao = new TestTableDao(testTableDaoConfig, this);

        registerDao(Activity.class, activityDao);
        registerDao(TestTable.class, testTableDao);
    }
    
    public void clear() {
        activityDaoConfig.getIdentityScope().clear();
        testTableDaoConfig.getIdentityScope().clear();
    }

    public ActivityDao getActivityDao() {
        return activityDao;
    }

    public TestTableDao getTestTableDao() {
        return testTableDao;
    }

}
